default:
  image: node:26

stages:
  - lint
  - test
  - build

lint:
  stage: lint
  cache:
    key: npm-$CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
  script:
    - npm ci
    - npm run lint

test:
  stage: test
  cache:
    key: npm-$CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
  script:
    - npm ci
    - npm test

build:
  stage: build
  cache:
    key: npm-$CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 week
