#!/bin/bash
#
# creates the common.js file


getallfiles(){
    find */* -name '*.js' -not -path 'lib/require.js' -not -path '*/test/*.js' | grep -v 'jquery'
}

getrequirefiles(){
	  grep -Pl 'define\((?!\))' `getallfiles`
}

getrequirepaths(){
    getrequirefiles | sed 's/\.js$//'
}

formatpatharray(){
    echo "["
    getrequirepaths | sed -e 's/^\|$/"/g' -e 's/^/  /' -e '$q;s/$/,/'
    echo "]"
}

createDefine(){
    cat <<EOF
/**
* common.js: loads EVERY require-js compatible file from this folder
* 
* This file is automatically generated by createcommon.sh
*/

define(`formatpatharray`);

EOF
}

createDefine > common.js
