/**
 * common.js: loads each requirejs-compatible script file
 *
 * This file is automatically generated as part of the build process.
 * Do not attempt manual changes, they'll be overwritten
 *
 * @return Common
 * @author Erik E. Lorenz <erik.e.lorenz@gmail.com>
 * @license MIT License
 * @see LICENSE
 */

var modules = [
    { modules }
];

define(modules, function() {
    var loaded = {};
    for (let i = 0; i < arguments.length; i += 1) {
        loaded[modules[i]] = arguments[i];
    }

    var Common = function(str) {
        var module = loaded[str] || require.s.contexts._.defined[str];
        if (!module) {
            throw new Error("module '" + str + "' is undefined, not loaded or equals 0 in some way => " + module);
        }
        return module;
    };

    return Common;
});
