#!/bin/bash
#
# creates the common.js and test.js files

cd scripts || exit 1

createTestJS(){
    files=$(echo ./*/{*/,}test/*.js | xargs -n1 | sed -e "s/^/         '/" -e "s/\.js\$/',/")

    cat << EOF
/**
 * Run every available test
 *
 * This file is automatically created on build. Do not attempt manual changes
 */

define([ 'common',
         'lib/qunit',
$files ], function(Common, QUnit){
  var i;
  for (i = 2; i < arguments.length; i += 1) {
    arguments[i](QUnit, Common);
  }
  QUnit.load();
  QUnit.start();
});
EOF
}


getallfiles(){
    find */* -name '*.js' -not -path 'lib/require.js' -not -path '*/test/*.js' | grep -v 'jquery'
}

getrequirefiles(){
	  grep -Pl 'define\((?!\))' `getallfiles`
}

getrequirepaths(){
    getrequirefiles | sed 's/\.js$//'
}

formatpatharray(){
    echo "["
    getrequirepaths | sed -e 's/^\|$/"/g' -e 's/^/  /' -e '$q;s/$/,/'
    echo "]"
}

createCommonJS(){
    cat <<EOF
/**
 * common.js: loads each requirejs-compatible script file (except tests) and
 * configures requirejs to load libraries as shims
 *
 * This file is automatically generated as part of the build process.
 * Do not attempt manual changes
 */

require.config({
  shim : {
    'lib/modernizr' : {
      deps: ['lib/Blob'],
      exports: 'Modernizr'
    },
      'lib/Blob' : {
      exports : 'Blob'
    },
      'lib/typeahead' : {
//      deps: [ 'lib/jquery' ]
    },
    'lib/qunit' : {
      exports: 'QUnit',
      /**
      * disable QUnit autoload/autostart for requirejs optimizer compatibility
      */
      init: function() {
        QUnit.config.autoload = false;
        QUnit.config.autostart = false;
      }
    },
  },
});

define(`formatpatharray`, function (undefined){
  return function (str) {
    return require.s.contexts._.defined[str];
  };
});

EOF
}

getShim(){
    sed -n '/^\s*shim\s*:/,/})/p' common.js | sed '$s/;$//'
}

updateBuildJS(){
    newbuild=`sed -e '/^\s*shim\s*:/,$ d' ../build-scripts/build.js`
    cat <<EOF > ../build-scripts/build.js
$newbuild
`getShim`
EOF
}

createCommonJS > common.js
echo "common.js written"
createTestJS > test.js
echo "test.js written"
updateBuildJS
echo "build.js updated"
